## 임의의 입력 생성

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional
from tensorflow.keras.models import Sequential

In [2]:
## 단어의 벡터 차원은 5, 문장의 길이는 4인 경우를 가정
## = 4번의 시점 (timesteps) 이 존재하고, 각 시점마다 5차원의 단어 벡터가 입력으로 사용됨
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], 
           [1.0, 3.1, 2.5, 0.7, 1.1], 
           [0.3, 2.1, 1.5, 2.1, 0.1], 
           [2.2, 1.4, 0.5, 0.9, 1.1]]

In [6]:
np.shape(train_X)

(4, 5)

In [29]:
## RNN은 3D 텐서를 입력받기 때문에 batch_size=1 를 추가하여 2D 텐서 => 3D 텐서로 변경
## batch_size=1 은 현재 샘플이 한 개 밖에 없기 때문에 임의로 설정한 값!
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], 
            [1.0, 3.1, 2.5, 0.7, 1.1], 
            [0.3, 2.1, 1.5, 2.1, 0.1], 
            [2.2, 1.4, 0.5, 0.9, 1.1]]]
            
train_X = np.array(train_X, dtype=np.float32)

In [30]:
## (batch_size, timesteps, input_dim) = (1, 4, 5)
np.shape(train_X)

(1, 4, 5)

## SimpleRNN

- 위에서 임의로 생성한 데이터를 SimpleRNN의 입력으로 하여 출력값을 생성함

- 은닉 상태 = 3
- return_sequences = False
- return_state = False


In [33]:
## SimpleRNN의 대표적인 인자
## 1) return_sequences=False
## 2) return_state=False

## 은닉 상태의 크기를 3으로 지정
rnn = SimpleRNN(3) # = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state = rnn(train_X)

print(hidden_state)
print(hidden_state.shape) ## 은닉 상태=3, return_sequences=False => 마지막 시점의 은닉 상태만 출력 => (1, 3) 크기의 텐서 반환

tf.Tensor([[-0.99920297 -0.90079504 -0.63070214]], shape=(1, 3), dtype=float32)
(1, 3)


- 은닉 상태 = 3
- return_sequences = True
- return_state = False


In [37]:
rnn = SimpleRNN(3, return_sequences=True) # = SimpleRNN(3, return_sequences=True, return_state=False)와 동일.
hidden_state = rnn(train_X)

print(hidden_state)
print(hidden_state.shape) ## 은닉 상태=3, return_sequences=True => 모든 시점의 은닉 상태 출력 => (1, 4, 3) 크기의 텐서 반환

tf.Tensor(
[[[ 0.96075356 -0.99996823 -0.91444737]
  [ 0.83762455 -0.99996656 -0.5097923 ]
  [ 0.1969568  -0.96925104  0.9248392 ]
  [ 0.61809283 -0.66473997 -0.62028956]]], shape=(1, 4, 3), dtype=float32)
(1, 4, 3)


- 은닉 상태 = 3
- return_sequences = False
- return_state = True

In [40]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_states, last_state = rnn(train_X)

## return_sequences=False 에 의한 마지막 시점 은닉 상태
print(hidden_states)
print(hidden_states.shape) ## 은닉 상태=3, return_state=True => return_state=True 이면 return_sequences 값에 상관없이 마지막 시점의 은닉 상태 출력
## return_state=True 에 의한 마지막 시점 은닉 상태
print(last_state)
print(last_state.shape)

tf.Tensor([[ 0.83888245  0.29763344 -0.8472526 ]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[ 0.83888245  0.29763344 -0.8472526 ]], shape=(1, 3), dtype=float32)
(1, 3)


- 은닉 상태 = 3
- return_sequences = True
- return_state = True

In [38]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

## return_sequences=True 에 의한 모든 시점 은닉 상태
print(hidden_states)
print(hidden_states.shape) ## 은닉 상태=3, return_state=True => return_state=True 이면 return_sequences 값에 상관없이 마지막 시점의 은닉 상태 출력
## return_state=True 에 의한 마지막 시점 은닉 상태
print(last_state)
print(last_state.shape)

tf.Tensor(
[[[ 0.25307786 -0.99758774  0.99185723]
  [ 0.06171196 -0.998129    0.9762221 ]
  [ 0.6062321  -0.9971669   0.94836664]
  [ 0.48797077 -0.9983326   0.989138  ]]], shape=(1, 4, 3), dtype=float32)
(1, 4, 3)
tf.Tensor([[ 0.48797077 -0.9983326   0.989138  ]], shape=(1, 3), dtype=float32)
(1, 3)


## LSTM

- 은닉 상태 = 3
- return_sequences = False
- return_state = False

In [41]:
lstm = LSTM(3)
hidden_state = lstm(train_X)

print(hidden_state)
print(hidden_state.shape)

tf.Tensor([[-0.02579624 -0.05711701 -0.31112766]], shape=(1, 3), dtype=float32)
(1, 3)


- 은닉 상태 = 3
- return_sequences = True
- return_state = False

In [42]:
lstm = LSTM(3, return_sequences=True)
hidden_state = lstm(train_X)

print(hidden_state)
print(hidden_state.shape)

tf.Tensor(
[[[-0.52221864 -0.44488105 -0.23758584]
  [-0.33502948 -0.6736479  -0.2429331 ]
  [ 0.08276625 -0.78515166 -0.18412358]
  [-0.21635228 -0.29922092 -0.39098972]]], shape=(1, 4, 3), dtype=float32)
(1, 4, 3)


- 은닉 상태 = 3
- return_sequences = False
- return_state = True

In [43]:
lstm = LSTM(3, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

## 마지막 시점 은닉 상태
print(hidden_state)
print(hidden_state.shape)
## 마지막 시점 은닉 상태
print(last_state)
print(last_state.shape)
## 마지막 셀 상태
print(last_cell_state) 
print(last_cell_state.shape)

tf.Tensor([[-2.9086057e-05  2.1537215e-01  5.2070860e-02]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[-2.9086057e-05  2.1537215e-01  5.2070860e-02]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[-1.3716891e-04  2.8001732e-01  1.5381490e-01]], shape=(1, 3), dtype=float32)
(1, 3)


- 은닉 상태 = 3
- return_sequences = True
- return_state = True

In [44]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

## 모든 시점 은닉 상태
print(hidden_state)
print(hidden_state.shape)
## 마지막 시점 은닉 상태
print(last_state)
print(last_state.shape)
## 마지막 셀 상태
print(last_cell_state) 
print(last_cell_state.shape)

tf.Tensor(
[[[ 0.01266283 -0.01073732 -0.26956397]
  [ 0.06335244  0.0129718  -0.29681572]
  [ 0.06446633  0.13837092 -0.19866091]
  [ 0.15899025  0.26276284 -0.18384273]]], shape=(1, 4, 3), dtype=float32)
(1, 4, 3)
tf.Tensor([[ 0.15899025  0.26276284 -0.18384273]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[ 0.32054126  0.3726378  -0.78897256]], shape=(1, 3), dtype=float32)
(1, 3)


## 양방향 LSTM

- 출력되는 은닉 상태 값 고정

In [45]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

- 은닉 상태 = 3
- return_sequences = False
- return_state = False

In [47]:
bilstm = Bidirectional(LSTM(3, 
                            return_sequences=False, 
                            return_state=False,
                            kernel_initializer=k_init, 
                            bias_initializer=b_init, 
                            recurrent_initializer=r_init))

hidden_states = bilstm(train_X)

print(hidden_states)
print(hidden_states.shape)

tf.Tensor([[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape=(1, 6), dtype=float32)
(1, 6)


- 은닉 상태 = 3
- return_sequences = True
- return_state = False

In [48]:
bilstm = Bidirectional(LSTM(3, 
                            return_sequences=True, 
                            return_state=False,
                            kernel_initializer=k_init, 
                            bias_initializer=b_init, 
                            recurrent_initializer=r_init))

hidden_states = bilstm(train_X)

print(hidden_states)
print(hidden_states.shape)

tf.Tensor(
[[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape=(1, 4, 6), dtype=float32)
(1, 4, 6)


- 은닉 상태 = 3
- return_sequences = False
- return_state = True

In [49]:
bilstm = Bidirectional(LSTM(3, 
                            return_sequences=False, 
                            return_state=True,
                            kernel_initializer=k_init, 
                            bias_initializer=b_init, 
                            recurrent_initializer=r_init))

## return_state=True 일 때, 정향향 LSTM과 역방향 LSTM의 은닉 상태 및 셀 상태 모두를 반환함
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

## hidden states
print(hidden_states)
print(hidden_states.shape)

## forward state
print(forward_h)  ## 정방향 LSTM의 마지막 시점의 은닉 상태 값
print(forward_h.shape)

## backward state
print(backward_h) ## 역방향 LSTM의 첫 번째 시점의 은닉 상태 값
print(backward_h.shape)

tf.Tensor([[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape=(1, 6), dtype=float32)
(1, 6)
tf.Tensor([[0.63031393 0.63031393 0.63031393]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[0.7038734 0.7038734 0.7038734]], shape=(1, 3), dtype=float32)
(1, 3)


- 은닉 상태 = 3
- return_sequences = True
- return_state = True

In [50]:
bilstm = Bidirectional(LSTM(3, 
                            return_sequences=True, 
                            return_state=True,
                            kernel_initializer=k_init, 
                            bias_initializer=b_init, 
                            recurrent_initializer=r_init))

## return_state=True 일 때, 정향향 LSTM과 역방향 LSTM의 은닉 상태 및 셀 상태 모두를 반환함
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

## hidden states
print(hidden_states) ## return_sequences=True 이므로 모든 시점의 은닉 상태를 출력
print(hidden_states.shape)

## forward state
print(forward_h)  ## 정방향 LSTM의 마지막 시점의 은닉 상태 값
print(forward_h.shape)

## backward state
print(backward_h) ## 역방향 LSTM의 첫 번째 시점의 은닉 상태 값
print(backward_h.shape)

tf.Tensor(
[[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape=(1, 4, 6), dtype=float32)
(1, 4, 6)
tf.Tensor([[0.63031393 0.63031393 0.63031393]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[0.7038734 0.7038734 0.7038734]], shape=(1, 3), dtype=float32)
(1, 3)
