### 환경 설정

In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn
#import tensorflow as tf
from sklearn.model_selection import train_test_split

### numpy

In [ ]:
array1 = np.array([1, 2, 3]) # 1차원 array로 3개의 데이터를 가지고 있음.
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [ ]:
array2 = np.array([
                   [1, 2, 3],
                   [2, 3, 4]
])
print(array2)
print(type(array2))
print(array2.shape)

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
array3 = np.array([
                   [1, 2, 3] # 2차원 array임. # array1과 동일한 데이터 건수를 가지고 있지만 다른 배열임.
])
print(array3)
print(type(array3))
print(array3.shape)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
## 배열의 차원 확인하기. => ndim
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [ ]:
list1 = [1, 2, 3]
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.dtype) # array 내의 데이터 타입 확인. => dtype

[1 2 3]
<class 'numpy.ndarray'>
int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2)         # ndarray 내의 데이터 타입은 같은 데이터 타입만 가능함.
print(type(array2))   # int형 => string형으로 변환됨.     
print(array2.dtype)

['1' '2' 'test']
<class 'numpy.ndarray'>
<U21


In [ ]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3)
print(type(array3))   # int형 => float형으로 변환됨.
print(array3.dtype)

[1. 2. 3.]
<class 'numpy.ndarray'>
float64


In [ ]:
## ndarray 내의 데이터 타입 변경하기. => astype
array_int = np.array([1, 2, 3])
print(array_int)
array_float = array_int.astype('float64')
print(array_float)
array_int = array_float.astype('int32')
print(array_int)

[1 2 3]
[1. 2. 3.]
[1 2 3]


In [ ]:
## ndarray 생성하기. => arange
array1 = np.arange(10)
print(array1)
print(array1.dtype)
print(array1.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)


In [ ]:
array2 = np.arange(2, 10)
print(array2)
print(array2.dtype)
print(array2.shape)

[2 3 4 5 6 7 8 9]
int64
(8,)


In [ ]:
## 0으로 채운 ndarray 생성. => zeros
## 튜플 형태의 shape 값과 dtype를 지정해 주어야 함. dtype default값은 float64임.
array1 = np.zeros((3, 2), dtype='int32')
print(array1)
print(array1.dtype)
print(array1.shape)

[[0 0]
 [0 0]
 [0 0]]
int32
(3, 2)


In [ ]:
## 1로 채운 ndarray 생성. => ones
## 튜플 형태의 shape 값과 dtype를 지정해 주어야 함. dtype default값은 float64임.
array2 = np.ones((3, 2))
print(array2)
print(array2.dtype)
print(array2.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
(3, 2)


In [ ]:
## ndarray의 차원과 크기를 변경하기. => reshape
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2, 5)
print(array2)

array3 = array1.reshape(5, 2)
print(array3)

array4 = array3.reshape(2, 5)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array2.reshape(5, -1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(1, -1)
print(array2) # reshape는 2차원 배열 형태로 반환함.

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
## 단일 값 추출하기. => []
array1 = np.arange(1, 10)
print(array1)
print(array1[2])
print(type(array1[2]))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>


In [ ]:
## 다차원 ndarray에서 단일 값 추출하기.
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)
print(array2[0, 0])
print(type(array2[0, 0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
<class 'numpy.int64'>


In [ ]:
## 슬라이싱 ([:])
array1 = np.arange(1, 10)
print(array1[0:3])
print(array1[:3])
print(array1[:1])
print(array1[3:])
print(array1[:])         # 시작/종료 인덱스 생략 가능.
print(type(array1[0:3])) # 타입은 ndarray 동일.
print(type(array1[:1]))

[1 2 3]
[1 2 3]
[1]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
## 다차원 배열의 슬라이싱. => [:, :]
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)
print(array2[0:2])
print(array2[0:2, :])
print(array2[0:2].ndim)
print(array2[0:2, :].ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
2
2


In [ ]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)
print(array2[0]) # 2차원 배열을 1차원 배열로 슬라이싱.
print(array2[1])
print(array2[0].ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
1


In [ ]:
## 펜시 인덱싱. => [[], :]
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print(array2)
print()

array3 = array2[[0, 1], 2]
print(array3)
print(type(array3))
print(array3.tolist())
print(type(array3.tolist()))
print()

array4 = array2[[0, 2], 1:3]
print(array4)
print(type(array4))
print(array4.tolist())
print(type(array4.tolist()))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6]
<class 'numpy.ndarray'>
[3, 6]
<class 'list'>

[[2 3]
 [8 9]]
<class 'numpy.ndarray'>
[[2, 3], [8, 9]]
<class 'list'>


In [ ]:
## 불린 인덱싱. => [>]
array1 = np.arange(1, 10)
print(array1[array1>5])
print(array1 > 5)

[6 7 8 9]
[False False False False False  True  True  True  True]


In [ ]:
## 행렬 정렬하기. => np.sort()
array1 = np.array([3, 1, 5, 9])
print(np.sort(array1))        # 오름차순.
print(np.sort(array1)[::-1])  # 내림차순.

[1 3 5 9]
[9 5 3 1]


In [ ]:
## 다차원 배열에서의 행렬 정렬하기.
array1 = np.array([
                   [8, 12],
                   [7, 1]
])
print(np.sort(array1))
print(np.sort(array1, axis=0))
print(np.sort(array1, axis=1))

print()

array2 = np.array([
                   [13, 12],
                   [7, 1]
])
print(np.sort(array2))
print(np.sort(array2, axis=0))  # 같은 열을 오름차순으로 정렬.
print(np.sort(array2, axis=1))  # 같은 행을 오름차순으로 정렬.

[[ 8 12]
 [ 1  7]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]

[[12 13]
 [ 1  7]]
[[ 7  1]
 [13 12]]
[[12 13]
 [ 1  7]]


In [ ]:
## 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환하기. => np.argsort()
array1 = np.array([3, 1, 5, 9])
array1_sort = np.sort(array1)
array1_argsort = np.argsort(array1) # 오름차순의 인덱스 반환. => np.argsort(원본 행렬)
print(array1_sort)
print(array1_argsort)

[1 3 5 9]
[1 0 2 3]


In [ ]:
array1 = np.array([3, 1, 5, 9])
print(np.argsort(array1)[::-1]) # 내림차순의 인덱스 반환. => np.argsort(원본 행렬)[::-1]

[3 2 0 1]


In [ ]:
## sort 예시.
name_array = np.array(['김철수', '박철수', '이철수', '반철수'])
score_array = np.array([33, 44, 11, 22])

# 성적이 오름차순으로 학생들을 정렬하기.
name_array[np.argsort(score_array)]

array(['이철수', '반철수', '김철수', '박철수'], dtype='<U3')

In [ ]:
## 행렬 내적(행렬 곱) => np.dot(A, B)
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

B = np.array([
              [1, 2],
              [3, 4],
              [5, 6]
])
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [ ]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

### pandas

In [66]:
import pandas as pd

In [65]:
titanic_df = pd.read_csv("/content/drive/MyDrive/데이터 분석 공부/data/titanic_train.csv")

In [ ]:
titanic_df.head(3) ## => head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
type(titanic_df) ## => type

pandas.core.frame.DataFrame

In [ ]:
titanic_df.shape ## => shape

(891, 12)

In [ ]:
titanic_df.info() ## => info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
titanic_df.describe() ## => describe() : 숫자형 칼럼에 대한 대략적인 데이터 분포도 확인.

# PassengerId => 1~891 num. 승객 ID를 식별하는 코드. 분석을 위한 유의미한 속성 아님.
# Survived    => min, 25%, 50%는 0이고, 75%, max가 1인 것으로 보아 0과 1로 이루어진 숫자형 카테고리 칼럼일 것임.
# Pclass      => 1, 2, 3으로 이루어진 숫자형 카테고리 칼럼일 것임.

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
## => Series, value_counts()
## DataFrame -> Series 변환, .value_counts()로 해당 칼럼값의 유형과 건수 확인.
titanic_df['Pclass'].value_counts() # 데이터 분포도 확인.

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
titanic_df['Pclass'].head(3)

0    3
1    1
2    3
Name: Pclass, dtype: int64

In [ ]:
## 1차원 형태의 리스트와 넘파이 ndarray를 DataFrame으로 변환하기. => pd.DataFrame(변환하고자 하는 리스트, ndarray, dictionary)
import numpy as np

col_name = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print(array1.shape) # 1차원 넘파이 데이터.

## DataFrame 생성하기.
df_list1 = pd.DataFrame(list1, columns=col_name)
df_array1 = pd.DataFrame(array1, columns=col_name)
print(df_list1)
print(df_array1)

(3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [ ]:
## 2차원 형태의 데이터로 DataFrame 생성하기.
col_name2 = ['col1', 'col2', 'col3']
list2 = [
         [1, 2, 3],
         [11, 12, 13]
]
array2 = np.array(list2)
print(array2.shape) # 2차원 형태의 넘파이 데이터.

df_list2 = pd.DataFrame(list2, columns=col_name2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print(df_list2)
print(df_array2)

(2, 3)
   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13


In [ ]:
## 딕셔너리 데이터를 DataFrame으로 변환하기.
## (단, 일반적으로 key(칼럼명 -> 문자열), value(키에 해당하는 칼럼 데이터 -> 리스트, ndarray)로 변환됨.)
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


In [ ]:
## DataFrame을 ndarray로 변환하기. => values
array3 = df_dict.values
print(type(array3))
print(array3.shape)
print(array3)

<class 'numpy.ndarray'>
(2, 3)
[[ 1  2  3]
 [11 22 33]]


In [ ]:
## DataFrame을 list로 변환하기. => values.tolist()
list3 = df_dict.values.tolist()
print(list3)

## DataFrame을 dictionary로 변환하기. => to_dict('list')
dict3 = df_dict.to_dict('list')
print(dict3)

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [ ]:
## DataFrame 칼럼 생성하기. => df['새로운 칼럼 명'] = 값
print('칼럼 추가 후:')
titanic_df['Age_0'] = 0 # 'Age_0 칼럼 추가 후, 일괄적으로 0 할당하기.
titanic_df.head(3)

칼럼 추가 후:


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [ ]:
## 기존의 칼럼 Series 데이터를 이용하여 새로운 칼럼 Series 생성하기.
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0      220.0  
1      0          PC 17599  71.2833   C85        C      0      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0

In [ ]:
## 특정 컬럼 삭제. => df.drop(칼럼명, axis=1)
## 특정 데이터 삭제. => df.drop(로우명, axis=0)
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      220.0  
1      0          PC 17599  71.2833   C85        C      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0

In [ ]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0      220.0  
1      0          PC 17599  71.2833   C85        C      0      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0

In [ ]:
## 자신의 DataFrame 데이터 삭제. => inplace=True 설정.
titanic_df.drop(['Age_0', 'Age_by_10'], axis=1, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
titanic_df.drop([0, 1, 2], axis=0, inplace=True) # 
titanic_df.head(3)

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q

In [ ]:
# 원본 파일 다시 로딩.
titanic_df = pd.read_csv("/content/drive/MyDrive/데이터 분석 공부/data/titanic_train.csv")
# Index 객체 추출.
indexes = titanic_df.index
print(indexes)
print(type(indexes))
# Index 객체를 실제 값 array로 변환.
print(indexes.values)
print(type(indexes))
print(indexes.shape)
print(indexes[:6].values)
print(indexes.values[:6])
print(indexes[6])

RangeIndex(start=0, stop=891, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 22

In [ ]:
series_fair = titanic_df['Fare']
print(series_fair.head(3))
print()

print(series_fair.max())
print(series_fair.sum())
print(sum(series_fair))
print((series_fair + 3).head(3))

0     7.2500
1    71.2833
2     7.9250
Name: Fare, dtype: float64

512.3292
28693.9493
28693.949299999967
0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [ ]:
## index reset => inplace=False(default)는 기존 인덱스를 칼럼으로 추가하고 인덱스 리셋. / inplace=True는 기존 인덱스 삭제 후 리셋.
df = titanic_df.reset_index() 
df.head(5)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   
3      3            4         1       1   
4      4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
## pandas 단일 데이터 추출. => df[칼럼명]
titanic_df['Pclass'].head(5)

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [ ]:
## 여러 칼럼의 데이터 추출. => df[[칼럼1, 칼럼2]]
titanic_df[['Survived', 'Pclass']].head(5)

Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3

In [ ]:
## 특정 데이터 추출. => df[i:j]
titanic_df[3:6]

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q

In [ ]:
## 불린 인덱싱. => df[df[칼럼명]==3].head()
titanic_df[titanic_df['Pclass']==3].head(5)

PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male   
2            3         1       3          Heikkinen, Miss. Laina  female   
4            5         0       3        Allen, Mr. William Henry    male   
5            6         0       3                Moran, Mr. James    male   
7            8         0       3  Palsson, Master. Gosta Leonard    male   

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0  22.0      1      0         A/5 21171   7.2500   NaN        S  
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4  35.0      0      0            373450   8.0500   NaN        S  
5   NaN      0      0            330877   8.4583   NaN        Q  
7   2.0      3      1            349909  21.0750   NaN        S

In [ ]:
data = { # dictionary data.
    'Name':['김영희', '이영희', '박영희', '반영희'],
    'Year':[1999, 2000, 2001, 1999],
    'Gender':['Male', 'Female', 'Male', 'Female']
}

data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four']) # DataFrame으로 변환.
data_df

Name  Year  Gender
one    김영희  1999    Male
two    이영희  2000  Female
three  박영희  2001    Male
four   반영희  1999  Female

In [ ]:
## => iloc[행 인덱스, 열 인덱스] : 인덱스를 기반으로 데이터를 추출함.
print(data_df.iloc[0, 0])
print(data_df.iloc[1, 1])

print()

print(data_df.iloc[0:2, 1:3])

김영희
2000

     Year  Gender
one  1999    Male
two  2000  Female


In [ ]:
## => loc[로우명, 칼럼명] : 명칭 기반으로 데이터를 추출함.
print(data_df.loc['four', 'Name'])

반영희


In [ ]:
## => loc & 슬라이싱
print(data_df.loc['one':'three', 'Name'])

one      김영희
two      이영희
three    박영희
Name: Name, dtype: object


In [70]:
## 불린 인덱싱.
titanic_df = pd.read_csv("/content/drive/MyDrive/데이터 분석 공부/data/titanic_train.csv")
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head(5)

Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [71]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(5)

Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [72]:
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [75]:
## DataFrame, Series 정렬하기. => sort_values()
titanic_df.sort_values(by=['Name'], ascending=False).head(3) # name 칼럼 내림차순 정렬.

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
361          362         0       2        del Carlo, Mr. Sebastiano  male   

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
868   NaN      0      0         345777   9.5000   NaN        S  
153  40.5      0      2       A/5. 851  14.5000   NaN        S  
361  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C

In [77]:
## DataFrame의 Aggregation 함수. => min(), max(), sum(), count()
print(titanic_df['Age'].min())
print(titanic_df['Age'].max())
print(titanic_df['Age'].sum())
print(titanic_df['Age'].count())

print()

print(titanic_df.count())

0.42
80.0
21205.17
714

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64


In [78]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [79]:
## => groupby()
titanic_df.groupby('Pclass')['Age'].min()

Pclass
1    0.92
2    0.67
3    0.42
Name: Age, dtype: float64

In [80]:
## => groupby()
titanic_df.groupby('Pclass')['Age'].agg(['max', 'min'])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [81]:
## => agg & groupby()
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [82]:
## 데이터 결측치 확인. => isna()
titanic_df.isna().head(5)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   
3        False     False   False  False  False  False  False  False   False   
4        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False  
3  False  False     False  
4  False   True     False

In [83]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [90]:
## 결측치 대체하기. => fillna()
titanic_df['Cabin'].fillna('C000', inplace=True) 
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  C000        S

In [91]:
print(titanic_df.isna().sum())
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True) # 평균값으로 결측치 채우기.

print(titanic_df.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64


In [92]:
## => lambda
return_value = lambda x : x**2
print('3의 제곱:', return_value(3))

3의 제곱: 9


In [95]:
a = [1, 2, 3]
result = map(lambda x : x**2, a)
list(result)

[1, 4, 9]

In [97]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [98]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x > 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(5)

Age Child_Adult
0  22.0       Child
1  38.0       Child
2  26.0       Child
3  35.0       Child
4  35.0       Child